-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(PRODUCT_ID) AS CNT
        FROM ONLINE_SALE
        GROUP BY USER_ID, PRODUCT_ID HAVING CNT >= 2
        ) AS Z
ORDER BY USER_ID ASC, PRODUCT_ID DESC