-- 코드를 입력하세요
# 연 | 월 | 상품 구매한 사람 수 / 총 2021년 가입자 수 


# SELECT COUNT(*)
# FROM USER_INFO
# WHERE YEAR(JOINED) = '2021';


# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(USER_ID)) AS PURCHASED_USERS
# FROM ONLINE_SALE
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)

SELECT YEAR, MONTH, PURCHASED_USERS, ROUND(PURCHASED_USERS/TOTAL,1) AS PURCHASED_RATIO
FROM (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(USER_ID)) AS PURCHASED_USERS
    FROM ONLINE_SALE 
    WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED)='2021')
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)) A
CROSS JOIN (SELECT COUNT(*) AS TOTAL FROM USER_INFO WHERE  YEAR(JOINED) = '2021') B
ORDER BY YEAR ASC, MONTH ASC
